#!/usr/bin/env bash
# Wrapper to run Cypress tests the way *I* want

SPEC="**/*"
HEADED=""
CFG_OPTS=""

for ARG in "$@"; do
  case "$ARG" in
    --headed) HEADED="--headed" ;;
    --video)  CFG_OPTS="$CFG_OPTS --config video=true" ;;
    --no-video) CFG_OPTS="$CFG_OPTS --config video=false" ;;
    --compression=*)  CFG_OPTS="$CFG_OPTS --config videoCompression=${ARG#*=}" ;;
    --videosFolder=*) CFG_OPTS="$CFG_OPTS --config videosFolder=${ARG#*=}" ;;
    -h|--help)
      echo "Usage: bash start [specPattern] [--headed] [--video|--no-video] [--compression=N] [--videosFolder=path]"
      exit 0
      ;;
    *) SPEC="$ARG" ;;
  esac
done

npx cypress run --spec "cypress/integration/$SPEC" $HEADED $CFG_OPTS
