// Random-donor + CSV-string generator for the CSV upload spec.
//
// Every generated donor satisfies the Phase-2 client rules AND the backend rules, so each
// row inserts with 201. Hall is pinned to the tester's own hall (not random) so the tester
// can always view the donor via "See Donor", making that assertion deterministic. Phones
// are suffixed from Date.now() so reruns never collide.

// The seeded super-admin tester lives in Suhrawardy hall (see clearDatabase.ts). Pinning
// every generated donor here keeps them viewable regardless of the caller's permissions.
export const TESTER_HALL = 'Suhrawardy';

export const CANONICAL_HEADERS = [
  'name', 'phone', 'studentId', 'bloodGroup', 'hall', 'roomNumber', 'address',
  'comment', 'donationCount', 'lastDonation', 'plateletDonationCount',
  'lastPlateletDonation', 'availableToAll'
] as const;

const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];
// Department codes accepted by the backend (the authoritative list). Every value is also
// <= departments.length, so it clears the client-side single-donor check too.
const ALLOWED_DEPT_CODES = ['00', '01', '02', '04', '05', '06', '08', '10', '11', '12', '15', '16', '17', '18'];
// Batch years comfortably <= the current year.
const BATCH_YEARS = ['16', '17', '18', '19', '20', '21', '22'];

export interface GeneratedDonor {
  name: string;
  phone: string; // 11-digit 01XXXXXXXXX
  studentId: string; // 7 digits
  bloodGroup: string;
  hall: string;
  roomNumber: string;
  address: string;
  comment: string;
  donationCount: string;
  lastDonation: string;
  plateletDonationCount: string;
  lastPlateletDonation: string;
  availableToAll: string;
}

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function digits(n: number): string {
  let s = '';
  for (let i = 0; i < n; i++) s += Math.floor(Math.random() * 10);
  return s;
}

export function generateDonors(count = 5): GeneratedDonor[] {
  const base = Date.now();
  const donors: GeneratedDonor[] = [];
  for (let i = 0; i < count; i++) {
    const uniqueTail = String(base + i).slice(-8); // 8 digits, unique per donor and per run
    const operator = pick(['6', '7', '8']);
    const phone = '01' + operator + uniqueTail; // 2 + 1 + 8 = 11 digits, starts 01
    const studentId = pick(BATCH_YEARS) + pick(ALLOWED_DEPT_CODES) + digits(3);
    donors.push({
      name: 'CSV Donor ' + uniqueTail,
      phone,
      studentId,
      bloodGroup: pick(BLOOD_GROUPS),
      hall: TESTER_HALL,
      roomNumber: 'Room ' + digits(3),
      address: 'Address ' + uniqueTail,
      comment: 'Generated by cypress',
      donationCount: '0',
      lastDonation: '',
      plateletDonationCount: '0',
      lastPlateletDonation: '',
      // availableToAll so the donor matches the home page's default "Public Data" search
      // (the same reason the single-donor spec ticks Public Data on its donor).
      availableToAll: 'yes'
    });
  }
  return donors;
}

// Serialize donors to a CSV string under the canonical header. Generated fields never
// contain commas or quotes, so a plain join is byte-compatible with the uploader.
export function donorsToCsv(donors: GeneratedDonor[]): string {
  const lines = [CANONICAL_HEADERS.join(',')];
  for (const donor of donors) {
    lines.push(CANONICAL_HEADERS.map((h) => donor[h]).join(','));
  }
  return lines.join('\n') + '\n';
}
